In [1]:
import random
import numpy as np

from math import log
log2 = lambda x: log(x)/log(2)

# Tensors

In [2]:
# for arbitrary precision ints

DTYPE = 'object'
Q = 503928829565480993

# we need room for summing MAX_SUM values of MAX_DEGREE before during modulus reduction
MAX_DEGREE = 2
MAX_SUM = 2**10
assert MAX_DEGREE * log2(Q) + log2(MAX_SUM) < 128

BASE = 2
PRECISION_INTEGRAL   = 10
PRECISION_FRACTIONAL = 16
# TODO Gap as needed for local truncating

# we need room for double precision before truncating
assert PRECISION_INTEGRAL + 2 * PRECISION_FRACTIONAL < log(Q)/log(BASE)

In [3]:
# for arbitrary precision ints

DTYPE = 'object'
Q = 2657003489534545107915232808830590043

# we need room for summing MAX_SUM values of MAX_DEGREE before during modulus reduction
MAX_DEGREE = 2
MAX_SUM = 2**12
assert MAX_DEGREE * log2(Q) + log2(MAX_SUM) < 256

BASE = 2
PRECISION_INTEGRAL   = 16
PRECISION_FRACTIONAL = 32
# TODO Gap as needed for local truncating

# we need room for double precision before truncating
assert PRECISION_INTEGRAL + 2 * PRECISION_FRACTIONAL < log(Q)/log(BASE)

In [4]:
def encode(rationals):
    return (rationals * BASE**PRECISION_FRACTIONAL).astype('int').astype(DTYPE) % Q

def decode(elements):
    map_negative_range = np.vectorize(lambda element: element if element <= Q/2 else element - Q)
    return map_negative_range(elements) / BASE**PRECISION_FRACTIONAL

In [5]:
class PublicTensor:
    
    def __init__(self, values):
        self.values = values
        
    def __repr__(self):
        return "PublicTensor(%s)" % decode(self.values)
    
    def load(values, apply_encoding=True):
        if apply_encoding: values = encode(values)
        return PublicTensor(values)
    
    def truncate(self, amount=PRECISION_FRACTIONAL):
        truncate = np.vectorize(lambda x: x // BASE**amount if x <= Q/2 else Q - ((Q - x) // BASE**amount))
        return PublicTensor(truncate(self.values))
    
    def add(x, y):
        if isinstance(y, PublicTensor):
            return PublicTensor((x.values + y.values) % Q)
        elif isinstance(y, PrivateTensor):
            shares0 = (x.values + y.shares0) % Q
            shares1 =             y.shares1
            return PrivateTensor(shares0, shares1)
        else:
            print(type(y))
            raise Error
        
    def __add__(x, y):
        return x.add(y)
        
    def sub(x, y):
        if isinstance(y, PublicTensor):
            return PublicTensor((x.values - y.values) % Q)
        elif isinstance(y, PrivateTensor):
            # TODO might be more efficient way
            shares0 = ((Q-1) * y.shares0 + x.values) % Q
            shares1 = ((Q-1) * y.shares1) % Q
            return PrivateTensor(shares0, shares1)
        elif isinstance(y, PublicTensor):
            shares0 = (x.shares0 - y.values) % Q
            shares1 =  x.shares1
            return PrivateTensor(shares0, shares1)
        else:
            print(type(y))
            raise Error
        
    def __sub__(x, y):
        return x.sub(y)
        
    def mul(x, y, truncate=True):
        if isinstance(y, PublicTensor):
            values = (x.values * y.values) % Q
            z = PublicTensor(values)
            if truncate: z = z.truncate()
            return z
        elif isinstance(y, PrivateTensor):
            shares0 = (x.values * y.shares0) % Q
            shares1 = (x.values * y.shares1) % Q
            z = PrivateTensor(shares0, shares1)
            if truncate: z = z.truncate()
            return z
        else:
            print(type(y))
            raise Error
    
    def __mul__(x, y):
        return x.mul(y)
    
    def dot(x, y, truncate=True):
        if isinstance(y, PublicTensor):
            z = PublicTensor(x.values.dot(y.values) % Q)
            if truncate: z = z.truncate()
            return z
        elif isinstance(y, PrivateTensor):
            shares0 = x.values.dot(y.shares0) % Q
            shares1 = x.values.dot(y.shares1) % Q
            z = PrivateTensor(shares0, shares1)
            if truncate: z = z.truncate()
            return z
        else:
            print(type(y))
            raise Error
        
    def transpose(self):
        return PublicTensor(self.values.T)
    
    def sum0(self):
        values = self.values.sum(axis=0, keepdims=True)
        return PublicTensor(values)

In [6]:
x = PublicTensor.load(np.array([1,2,3,4]).reshape(4,1) - 2); print(x)
y = PublicTensor.load(np.array([5,6,7,8]).reshape(4,1)); print(y)
z = x + y; print(z)
z = (x * y); print(z)
z = x.dot(y.transpose()); print(z)
z = z.sum0(); print(z)

PublicTensor([[-1.]
 [ 0.]
 [ 1.]
 [ 2.]])
PublicTensor([[ 5.]
 [ 6.]
 [ 7.]
 [ 8.]])
PublicTensor([[  4.]
 [  6.]
 [  8.]
 [ 10.]])
PublicTensor([[ -5.]
 [  0.]
 [  7.]
 [ 16.]])
PublicTensor([[ -5.  -6.  -7.  -8.]
 [  0.   0.   0.   0.]
 [  5.   6.   7.   8.]
 [ 10.  12.  14.  16.]])
PublicTensor([[ 10.  12.  14.  16.]])


In [7]:
def generate_mul_triple(shape):
    a = np.array([ random.randrange(Q) for _ in range(np.prod(shape)) ]).astype(DTYPE).reshape(shape)
    b = np.array([ random.randrange(Q) for _ in range(np.prod(shape)) ]).astype(DTYPE).reshape(shape)
    ab = (a * b) % Q
    return PrivateTensor.load(a, False), \
           PrivateTensor.load(b, False), \
           PrivateTensor.load(ab, False)

In [8]:
def generate_dot_triple(m, n, o):
    a = np.array([ random.randrange(Q) for _ in range(m*n) ]).astype(DTYPE).reshape((m,n))
    b = np.array([ random.randrange(Q) for _ in range(n*o) ]).astype(DTYPE).reshape((n,o))
    ab = np.dot(a, b)
    return PrivateTensor.load(a, False), \
           PrivateTensor.load(b, False), \
           PrivateTensor.load(ab, False)

In [9]:
class PrivateTensor:
    
    def __init__(self, shares0, shares1):
        self.shares0 = shares0
        self.shares1 = shares1

    def load(values, apply_encoding=True):
        if apply_encoding: values = encode(values)
        shares0 = np.array([ random.randrange(Q) for _ in range(values.size) ]).astype(DTYPE).reshape(values.shape)
        shares1 = (values - shares0) % Q
        return PrivateTensor(shares0, shares1)

    def reveal(self):
        values = (self.shares0 + self.shares1) % Q
        return PublicTensor(values)
    
    def truncate(self, amount=PRECISION_FRACTIONAL):
        shares0 = np.floor_divide(self.shares0, BASE**amount)
        shares1 = Q - (np.floor_divide(Q - self.shares1, BASE**amount))
        return PrivateTensor(shares0, shares1)
    
    def __repr__(self):
        return "PrivateTensor(%s)" % decode(self.reveal().values)
    
    def add(x, y):
        if isinstance(y, PrivateTensor):
            shares0 = (x.shares0 + y.shares0) % Q
            shares1 = (x.shares1 + y.shares1) % Q
            return PrivateTensor(shares0, shares1)
        elif isinstance(y, PublicTensor):
            shares0 = (x.shares0 + y.values) % Q
            shares1 =  x.shares1
            return PrivateTensor(shares0, shares1)
        elif isinstance(y, np.ndarray):
            return x.add(PublicTensor.load(y))
        elif isinstance(y, int) or isinstance(y, float):
            return x.add(PublicTensor.load(np.array([y])))
        else:
            print(type(y))
            raise Error
        
    def __add__(x, y):
        return x.add(y)
    
    def sub(x, y):
        if isinstance(y, PrivateTensor):
            shares0 = (x.shares0 - y.shares0) % Q
            shares1 = (x.shares1 - y.shares1) % Q
            return PrivateTensor(shares0, shares1)
        elif isinstance(y, PublicTensor):
            shares0 = (x.shares0 - y.values) % Q
            shares1 =  x.shares1
            return PrivateTensor(shares0, shares1)
        elif isinstance(y, int):
            y = PublicTensor.load(np.array([y]))
            return x.sub(y)
        elif isinstance(y, float):
            y = PublicTensor.load(np.array([y]))
            return x.sub(y)
        else:
            print(type(y))
            raise Error
        
    def __sub__(x, y):
        return x.sub(y)
    
    def mul(x, y, truncate=True, precomputed=None):
        if isinstance(y, PrivateTensor):
            assert x.shares0.shape == x.shares1.shape == y.shares0.shape == y.shares1.shape
            if precomputed is None: precomputed = generate_mul_triple(x.shares0.shape)
            a, b, ab = precomputed
            alpha = (x - a).reveal()
            beta  = (y - b).reveal()
            z = alpha.mul(beta, truncate=False) + \
                alpha.mul(b, truncate=False) + \
                a.mul(beta, truncate=False) + \
                ab
            if truncate: z = z.truncate()
            return z
        elif isinstance(y, PublicTensor):
            shares0 = (x.shares0 * y.values) % Q
            shares1 = (x.shares1 * y.values) % Q
            z = PrivateTensor(shares0, shares1)
            if truncate: z = z.truncate()
            return z
        elif isinstance(y, np.ndarray):
            return x.mul(PublicTensor.load(y), truncate, precomputed)
        elif isinstance(y, int) or isinstance(y, float):
            return x.mul(PublicTensor.load(np.array([y])), truncate, precomputed)
        else:
            print(type(y))
            raise Error
        
    def __mul__(x, y):
        return x.mul(y)
        
    def dot(x, y, truncate=True, precomputed=None):
        if isinstance(y, PrivateTensor):
            assert x.shares0.shape == x.shares1.shape 
            assert y.shares0.shape == y.shares1.shape
            m = x.shares0.shape[0]
            n = x.shares0.shape[1]
            o = y.shares0.shape[1]
            assert n == y.shares0.shape[0]
            if precomputed is None: precomputed = generate_dot_triple(m, n, o)
            a, b, ab = precomputed
            alpha = (x - a).reveal()
            beta  = (y - b).reveal()
            z = alpha.dot(beta, truncate=False) + \
                alpha.dot(b, truncate=False) + \
                a.dot(beta, truncate=False) + \
                ab
            if truncate: z = z.truncate()
            return z
        elif isinstance(y, PublicTensor):
            shares0 = x.shares0.dot(y.values) % Q
            shares1 = x.shares1.dot(y.values) % Q
            z = PrivateTensor(shares0, shares1)
            if truncate: z = z.truncate()
            return z
        elif isinstance(y, np.ndarray):
            return x.dot(PublicTensor.load(y))
        else:
            print(type(y))
            raise Error
        
    def neg(self):
        return self.mul(PublicTensor(np.array([Q - 1])), truncate=False)
        
    def transpose(self):
        return PrivateTensor(self.shares0.T, self.shares1.T)
    
    def sum0(self):
        shares0 = self.shares0.sum(axis=0, keepdims=True) % Q
        shares1 = self.shares1.sum(axis=0, keepdims=True) % Q
        return PrivateTensor(shares0, shares1)

In [10]:
x = PrivateTensor.load(np.array([1,2,3,4]).reshape(4,1) - 2)
y = PrivateTensor.load(np.array([5,6,7,8]).reshape(4,1))
z = x + y; print(z)
z = (x * y); print(z)
z = x.dot(y.transpose()); print(z)
z = z.sum0(); print(z)

PrivateTensor([[  4.]
 [  6.]
 [  8.]
 [ 10.]])
PrivateTensor([[ -5.]
 [  0.]
 [  7.]
 [ 16.]])
PrivateTensor([[ -5.  -6.  -7.  -8.]
 [  0.   0.   0.   0.]
 [  5.   6.   7.   8.]
 [ 10.  12.  14.  16.]])
PrivateTensor([[ 10.  12.  14.  16.]])


In [11]:
class NumpyTensor:
    
    def __init__(self, values):
        self.values = values

    def load(values):
        return NumpyTensor(values)

    def reveal(self):
        return self.values
    
    def __repr__(self):
        return "NumpyTensor(%s)" % self.values
    
    def add(x, y):
        if isinstance(y, NumpyTensor):
            return NumpyTensor(x.values + y.values)
        elif isinstance(y, int):
            return NumpyTensor(x.values + y)
        elif isinstance(y, float):
            return NumpyTensor(x.values + y)
        elif isinstance(y, np.ndarray):
            return NumpyTensor(x.values + y)
        else:
            print(type(y))
            raise Error
        
    def __add__(x, y):
        return x.add(y)
    
    def sub(x, y):
        if isinstance(y, NumpyTensor):
            return NumpyTensor(x.values - y.values)
        elif isinstance(y, int):
            return NumpyTensor(x.values - y)
        elif isinstance(y, float):
            return NumpyTensor(x.values - y)
        elif isinstance(y, np.ndarray):
            return NumpyTensor(x.values - y)
        else:
            print(type(y))
            raise Error
        
    def __sub__(x, y):
        return x.sub(y)
    
    def mul(x, y):
        if isinstance(y, NumpyTensor):
            return NumpyTensor(x.values * y.values)
        elif isinstance(y, int):
            return NumpyTensor(x.values * y)
        elif isinstance(y, float):
            return NumpyTensor(x.values * y)
        elif isinstance(y, np.ndarray):
            return NumpyTensor(x.values * y)
        else:
            print(type(y))
            raise Error
        
    def __mul__(x, y):
        return x.mul(y)
        
    def dot(x, y):
        if isinstance(y, NumpyTensor):
            return NumpyTensor(x.values.dot(y.values))
        elif isinstance(y, int):
            return NumpyTensor(x.values.dot(y))
        elif isinstance(y, float):
            return NumpyTensor(x.values.dot(y))
        elif isinstance(y, np.ndarray):
            return NumpyTensor(x.values.dot(y))
        else:
            print(type(y))
            raise Error
        
    def transpose(self):
        return NumpyTensor(self.values.T)
    
    def neg(self):
        return NumpyTensor(0 - self.values)

    def sum0(self):
        return NumpyTensor(self.values.sum(axis=0, keepdims=True))

In [12]:
x = NumpyTensor.load(np.array([1,2,3,4]).reshape(4,1) - 2)
y = NumpyTensor.load(np.array([5,6,7,8]).reshape(4,1))
z = x + y; print(z)
z = (x * y); print(z)
z = x.dot(y.transpose()); print(z)
z = z.sum0(); print(z)

NumpyTensor([[ 4]
 [ 6]
 [ 8]
 [10]])
NumpyTensor([[-5]
 [ 0]
 [ 7]
 [16]])
NumpyTensor([[-5 -6 -7 -8]
 [ 0  0  0  0]
 [ 5  6  7  8]
 [10 12 14 16]])
NumpyTensor([[10 12 14 16]])


# CNNs

In [13]:
class Dense:
    
    def __init__(self, num_nodes, num_features, learning_rate=.1):
        self.learning_rate = learning_rate
        self.num_nodes = num_nodes
        self.num_features = num_features
        self.weights = None
        self.bias = None
        
    def initialize(self):
        self.weights = .1 * np.random.randn(self.num_features, self.num_nodes)
        self.bias = np.zeros((1, self.num_nodes))
        
    
#     def precompute_forward(self, batch_shape):
#         assert batch_shape[1] == self.num_features
#         dot_triple = generate_dot_triple(batch_shape[0], self.num_features, self.num_nodes)
#         return dot_triple
    
    def forward(self, x):
        out = x.dot(self.weights) + self.bias
        self.cache = x
        return out

    def backward(self, d_out):
        x = self.cache
        # compute gradients for internal parameters and update
        d_weights = x.transpose().dot(d_out)
        d_bias = d_out.sum0()
        self.weights = (d_weights * self.learning_rate).neg() + self.weights
        self.bias    =    (d_bias * self.learning_rate).neg() + self.bias
        # compute and return external gradient
        d_x = d_out.dot(self.weights.transpose())
        return d_x

In [14]:
class Sigmoid:
    
    def __init__(self):
        self.cache = None
    
    def initialize(self):
        pass
    
    def forward(self, x):
        w0 =  0.5
        w1 =  0.2159198015
        w3 = -0.0082176259
        w5 =  0.0001825597
        w7 = -0.0000018848
        w9 =  0.0000000072
        
        x2 = x  * x
        x3 = x2 * x
        x5 = x2 * x3
        x7 = x2 * x5
        x9 = x2 * x7
        
        out = x9*w9 + x7*w7 + x5*w5 + x3*w3 + x*w1 + w0
        self.cache = out
        return out
    
    def backward(self, d_out):
        out = self.cache
        d_x = d_out * out * (out.neg() + 1)
        return d_x

In [15]:
class Sequential:
    
    def __init__(self, layers):
        self.layers = layers
    
    def initialize(self):
        for layer in self.layers:
            layer.initialize()
    
    def forward(self, x, train=False):
        for layer in self.layers:
            x = layer.forward(x)
        return x
    
    def backward(self, y):
        for layer in reversed(self.layers):
            y = layer.backward(y)
            
    def fit(self, x_train, y_train, loss, epochs=1000):
        for epoch in range(epochs):
            y_pred = self.forward(x_train)
            dout = loss.derive(y_pred, y_train)
            self.backward(dout)
            
    def predict(self, X):
        return self.forward(X)

In [16]:
class Simple:
    
    def derive(self, y_pred, y_train):
        return y_pred - y_train

In [17]:
model = Sequential([
    Dense(4, 2),
    Sigmoid(),
    Dense(1, 4),
    Sigmoid()
])

In [18]:
x = PrivateTensor.load(np.array([
# x = NumpyTensor.load(np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
]))

y = PrivateTensor.load(np.array([[
# y = NumpyTensor.load(np.array([[
    0,
    0,
    1,
    1
]]).T)

model.initialize()

model.fit(x, y, Simple(), epochs=10000)

model.predict(x)

PrivateTensor([[ 0.01398182]
 [ 0.01002933]
 [ 0.98819944]
 [ 0.98568798]])