In [1]:
import random
import numpy as np

In [2]:
class NativeTensor:
    
    def __init__(self, values):
        self.backing = values
        
    def from_values(values):
        return NativeTensor(values)
    
    @property
    def size(self):
        return self.backing.size
    
    @property
    def shape(self):
        return self.backing.shape
    
    def __getitem__(self, index):
        return NativeTensor(self.backing[index])

    def reveal(self):
        return self
    
    def unwrap(self):
        return self.backing
    
    def __repr__(self):
        return "NativeTensor(%s)" % self.backing
    
    def wrap_if_needed(y):
        if isinstance(y, int) or isinstance(y, float):
            return NativeTensor.from_values(np.array([y]))
        if isinstance(y, np.ndarray):
            return NativeTensor.from_values(y)
        return y
    
    def add(x, y):
        y = NativeTensor.wrap_if_needed(y)
        
        if isinstance(y, NativeTensor):
            return NativeTensor(x.backing + y.backing)
        
        if isinstance(y, PublicEncodedTensor):
            return PublicEncodedTensor.from_values(x).add(y)
        
        if isinstance(y, SharedEncodedTensor):
            return PublicEncodedTensor.from_values(x).add(y)
        
        raise TypeError("%s does not support %s" % (type(x), type(y)))
        
    def __add__(x, y):
        return x.add(y)
    
    def sub(x, y):
        y = NativeTensor.wrap_if_needed(y)
        
        if isinstance(y, NativeTensor):
            return NativeTensor(x.backing - y.backing)
        
        if isinstance(y, PublicEncodedTensor):
            return PublicEncodedTensor.from_values(x).sub(y)
        
        if isinstance(y, SharedEncodedTensor):
            return PublicEncodedTensor.from_values(x).sub(y)
        
        raise TypeError("%s does not support %s" % (type(x), type(y)))
        
    def __sub__(x, y):
        return x.sub(y)
    
    def mul(x, y):
        y = NativeTensor.wrap_if_needed(y)
        
        if isinstance(y, NativeTensor):
            return NativeTensor(x.backing * y.backing)
        
        if isinstance(y, PublicEncodedTensor):
            return PublicEncodedTensor.from_values(x).mul(y)
        
        if isinstance(y, SharedEncodedTensor):
            return PublicEncodedTensor.from_values(x).mul(y)
        
        raise TypeError("%s does not support %s" % (type(x), type(y)))
        
    def __mul__(x, y):
        return x.mul(y)
        
    def dot(x, y):
        y = NativeTensor.wrap_if_needed(y)
        
        if isinstance(y, NativeTensor):
            return NativeTensor(x.backing.dot(y.backing))
        
        if isinstance(y, PublicEncodedTensor):
            return PublicEncodedTensor.from_values(x).dot(y)
        
        if isinstance(y, SharedEncodedTensor):
            return PublicEncodedTensor.from_values(x).dot(y)
        
        raise TypeError("%s does not support %s" % (type(x), type(y)))
        
    def div(x, y):
        y = NativeTensor.wrap_if_needed(y)
        
        if isinstance(y, NativeTensor):
            return NativeTensor(x.backing / y.backing)
        
        raise TypeError("%s does not support %s" % (type(x), type(y)))
        
    def __div__(x, y):
        return x.div(y)
        
    def transpose(x):
        return NativeTensor(x.backing.T)
    
    def neg(x):
        return NativeTensor(0 - x.backing)

    def sum0(x):
        return NativeTensor(x.backing.sum(axis=0, keepdims=True))
    
    def sum1(x):
        return NativeTensor(x.backing.sum(axis=1, keepdims=True))
    
    def exp(x):
        return NativeTensor(np.exp(x.backing))
    
    def log(x):
        return NativeTensor(np.log(x.backing))
    
    def inv(x):
        return NativeTensor(1. / x.backing)

In [3]:
# x = NativeTensor(np.array([1,2,3,4]).reshape(4,1) - 2)
# y = NativeTensor(np.array([5,6,7,8]).reshape(4,1))
# z = x + y; print(z)
# z = (x * y); print(z)
# z = x.dot(y.transpose()); print(z)
# z = z.sum0(); print(z)

# Field Tensors

In [4]:
DTYPE = 'object'
Q = 2657003489534545107915232808830590043

In [5]:
# class FieldTensor:
    
#     def __init__(self, elements):
#         if not isinstance(elements, np.ndarray):
#             elements = np.array([elements])
#         self.elements = elements

#     def __repr__(self):
#         return "FieldTensor(%s)" % self.elements
        
#     @property
#     def shape(self):
#         return self.elements.shape
    
#     def __getitem__(self, index):
#         return FieldTensor(self.elements[index])
    
#     def add(x, y):
#         if isinstance(y, FieldTensor):
#             return FieldTensor((x.elements + y.elements) % Q)
#         else:
#             raise TypeError(type(y))
        
#     def __add__(x, y):
#         return x.add(y)
        
#     def sub(x, y):
#         if isinstance(y, FieldTensor):
#             return FieldTensor((x.elements - y.elements) % Q)
#         else:
#             raise TypeError(type(y))
        
#     def __sub__(x, y):
#         return x.sub(y)
        
#     def mul(x, y):
#         if isinstance(y, FieldTensor):
#             return FieldTensor((x.elements * y.elements) % Q)
#         else:
#             raise TypeError(type(y))
    
#     def __mul__(x, y):
#         return x.mul(y)
        
#     def dot(x, y):
#         if isinstance(y, FieldTensor):
#             return FieldTensor(x.elements.dot(y.elements) % Q)
#         else:
#             raise TypeError(type(y))
        
#     def transpose(x):
#         return FieldTensor(x.elements.T)
    
#     def sum0(x):
#         return FieldTensor(x.elements.sum(axis=0, keepdims=True))
    
#     def sum1(x):
#         return FieldTensor(x.elements.sum(axis=1, keepdims=True))

In [6]:
class PublicFieldTensor:
    
    def __init__(self, elements):
        self.elements = elements

    def from_elements(elements):
        return PublicFieldTensor(elements)
        
    def __repr__(self):
        return "PublicFieldTensor(%s)" % self.elements

    @property
    def size(self):
        return self.elements.size
    
    @property
    def shape(self):
        return self.elements.shape
    
    def __getitem__(self, index):
        return PublicFieldTensor.from_elements(self.elements[index])
    
    def add(x, y):
        if isinstance(y, PublicFieldTensor):
            elements = (x.elements + y.elements) % Q
            return PublicFieldTensor.from_elements(elements)
        
        elif isinstance(y, SharedFieldTensor):
            shares0 = (x.elements + y.shares0) % Q
            shares1 =               y.shares1
            return SharedFieldTensor.from_shares(shares0, shares1)
        
        else:
            raise TypeError(type(y))
        
    def __add__(x, y):
        return x.add(y)
    
    def mul(x, y):
        if isinstance(y, PublicFieldTensor):
            elements = (x.elements * y.elements) % Q
            return PublicFieldTensor.from_elements(elements)
        
        if isinstance(y, SharedFieldTensor):
            shares0 = (x.elements * y.shares0) % Q
            shares1 = (x.elements * y.shares1) % Q
            return SharedFieldTensor.from_shares(shares0, shares1)
        
        else:
            raise TypeError(type(y))
    
    def __mul__(x, y):
        return x.mul(y)
    
    def dot(x, y):
        if isinstance(y, PublicFieldTensor):
            elements = (x.elements.dot(y.elements)) % Q
            return PublicFieldTensor.from_elements(elements)
        
        if isinstance(y, SharedFieldTensor):
            shares0 = (x.elements.dot(y.shares0)) % Q
            shares1 = (x.elements.dot(y.shares1)) % Q
            return SharedFieldTensor.from_shares(shares0, shares1)
        
        else:
            raise TypeError(type(y))

In [7]:
def share(elements):
    shares0 = np.array([ random.randrange(Q) for _ in range(elements.size) ]).astype(DTYPE).reshape(elements.shape)
    shares1 = (elements - shares0) % Q
    return shares0, shares1

In [8]:
class SharedFieldTensor:
    
    def __init__(self, elements, shares0=[], shares1=[]):
        if elements is not None:
            shares0, shares1 = share(elements)
        self.shares0 = shares0
        self.shares1 = shares1
        assert self.shares0.shape == self.shares1.shape
    
    def from_elements(elements):
        return SharedFieldTensor(elements)
    
    def from_shares(shares0, shares1):
        return SharedFieldTensor(None, shares0, shares1)
    
    def reveal(self):
        elements = (self.shares0 + self.shares1) % Q
        return PublicFieldTensor.from_elements(elements)
    
    def __repr__(self):
        return "SharedFieldTensor(%s)" % self.reveal().elements

    def __getitem__(self, index):
        return SharedFieldTensor.from_shares(self.shares0[index], self.shares1[index])
    
    @property
    def size(self):
        return self.shares0.size
    
    @property
    def shape(self):
        return self.shares0.shape
    
    def add(x, y):
        if isinstance(y, SharedFieldTensor):
            shares0 = (x.shares0 + y.shares0) % Q
            shares1 = (x.shares1 + y.shares1) % Q
            return SharedFieldTensor.from_shares(shares0, shares1)
        
        elif isinstance(y, PublicFieldTensor):
            shares0 = (x.shares0 + y.elements) % Q
            shares1 =  x.shares1
            return SharedFieldTensor.from_shares(shares0, shares1)
        
        else:
            raise TypeError(type(y))
        
    def __add__(x, y):
        return x.add(y)
    
    def mul(x, y):
        if isinstance(y, PublicFieldTensor):
            shares0 = (x.shares0 * y.elements) % Q
            shares1 = (x.shares1 * y.elements) % Q
            return SharedFieldTensor.from_shares(shares0, shares1)
        
        else:
            raise TypeError(type(y))
    
    def __mul__(x, y):
        return x.mul(y)
    
    def dot(x, y):
        if isinstance(y, PublicFieldTensor):
            shares0 = (x.shares0.dot(y.elements)) % Q
            shares1 = (x.shares1.dot(y.elements)) % Q
            return SharedFieldTensor.from_shares(shares0, shares1)
        
        else:
            raise TypeError(type(y))

# Encoded Tensors

In [9]:
from math import log
log2 = lambda x: log(x)/log(2)

# for arbitrary precision ints

# we need room for summing MAX_SUM values of MAX_DEGREE before during modulus reduction
MAX_DEGREE = 2
MAX_SUM = 2**12
assert MAX_DEGREE * log2(Q) + log2(MAX_SUM) < 256

BASE = 2
PRECISION_INTEGRAL   = 16
PRECISION_FRACTIONAL = 32
# TODO Gap as needed for local truncating

# we need room for double precision before truncating
assert PRECISION_INTEGRAL + 2 * PRECISION_FRACTIONAL < log(Q)/log(BASE)

In [10]:
def encode(rationals):
    return (rationals * BASE**PRECISION_FRACTIONAL).astype('int').astype(DTYPE) % Q

def decode(elements):
    map_negative_range = np.vectorize(lambda element: element if element <= Q/2 else element - Q)
    return map_negative_range(elements) / BASE**PRECISION_FRACTIONAL

In [122]:
class PublicEncodedTensor:
    
    def __init__(self, values, elements=None):
        if not values is None:
            if not isinstance(values, np.ndarray):
                values = np.array([values])
            elements = encode(values)
        assert isinstance(elements, np.ndarray), "%s, %s, %s" % (values, elements, type(elements))
        self.elements = elements
    
    def from_values(values):
        return PublicEncodedTensor(values)
    
    def from_elements(elements):
        return PublicEncodedTensor(None, elements)
    
    def __getitem__(self, index):
        return PublicEncodedTensor.from_elements(self.elements[index])
    
    @property
    def shape(self):
        return self.elements.shape
    
    @property
    def size(self):
        return self.elements.size
    
    def unwrap(self):
        return decode(self.elements)
    
    def __repr__(self):
        return "PublicEncodedTensor(%s)" % decode(self.elements)
    
    def reveal(self):
        return NativeTensor.from_values(decode(self.elements))
    
    def truncate(self, amount=PRECISION_FRACTIONAL):
        positive_numbers = (self.elements <= Q // 2).astype(int)
        elements = self.elements
        elements = (Q + (2 * positive_numbers - 1) * elements) % Q # x if x <= Q//2 else Q - x
        elements = np.floor_divide(elements, BASE**amount)         # x // BASE**amount
        elements = (Q + (2 * positive_numbers - 1) * elements) % Q # x if x <= Q//2 else Q - x
        return PublicEncodedTensor.from_elements(elements)
    
    def wrap_if_needed(y):
        if isinstance(y, int) or isinstance(y, float):
            return PublicEncodedTensor.from_values(np.array([y]))
        if isinstance(y, np.ndarray):
            return PublicEncodedTensor.from_values(y)
        if isinstance(y, NativeTensor):
            return PublicEncodedTensor.from_values(y.backing)
        return y
    
    def add(x, y):
        y = PublicEncodedTensor.wrap_if_needed(y)
        
        if isinstance(y, PublicEncodedTensor):
            return PublicEncodedTensor.from_elements((x.elements + y.elements) % Q)
        
        if isinstance(y, SharedEncodedTensor):
            shares0 = (x.elements + y.shares0) % Q
            shares1 =               y.shares1
            return SharedEncodedTensor.from_shares(shares0, shares1)
        
        raise TypeError("%s does not support %s" % (type(x), type(y)))
        
    def __add__(x, y):
        return x.add(y)
        
    def sub(x, y):
        y = PublicEncodedTensor.wrap_if_needed(y)
        
        if isinstance(y, PublicEncodedTensor):
            return PublicEncodedTensor.from_elements((x.elements - y.elements) % Q)
        
        if isinstance(y, SharedEncodedTensor):
            return x.add(y.neg()) # TODO there might be a more efficient way
            
        raise TypeError("%s does not support %s" % (type(x), type(y)))
        
    def __sub__(x, y):
        return x.sub(y)
        
    def mul(x, y):
        y = PublicEncodedTensor.wrap_if_needed(y)
        
        if isinstance(y, PublicEncodedTensor):
            return PublicEncodedTensor.from_elements((x.elements * y.elements) % Q).truncate()
        
        if isinstance(y, PublicFieldTensor):
            return PublicFieldTensor.from_elements((x.elements * y.elements) % Q)
    
        raise TypeError("%s does not support %s" % (type(x), type(y)))
    
    def __mul__(x, y):
        return x.mul(y)
    
    def dot(x, y):
        y = PublicEncodedTensor.wrap_if_needed(y)
        
        if isinstance(y, PublicEncodedTensor):
            return PublicEncodedTensor.from_elements(x.elements.dot(y.elements) % Q).truncate()

        raise TypeError("%s does not support %s" % (type(x), type(y)))
        
    def transpose(x):
        return PublicEncodedTensor.from_elements(x.elements.T)
    
    def sum0(x):
        return PublicEncodedTensor.from_elements(x.elements.sum(axis=0, keepdims=True))
    
    def sum1(x):
        return PublicEncodedTensor.from_elements(x.elements.sum(axis=1, keepdims=True))
    
    def neg(self):
        minus_one = PublicFieldTensor.from_elements(np.array([Q - 1]))
        z = self.mul(minus_one)
        return PublicEncodedTensor.from_elements(z.elements)

In [123]:
# x = PublicEncodedTensor(np.array([1,2,3,4]).reshape(4,1) - 2); print(x)
# y = PublicEncodedTensor(np.array([5,6,7,8]).reshape(4,1)); print(y)
# z = x + y; print(z)
# z = (x * y); print(z)
# z = x.dot(y.transpose()); print(z)
# z = z.sum0(); print(z)

PublicEncodedTensor([[-1.]
 [ 0.]
 [ 1.]
 [ 2.]])
PublicEncodedTensor([[ 5.]
 [ 6.]
 [ 7.]
 [ 8.]])
PublicEncodedTensor([[  4.]
 [  6.]
 [  8.]
 [ 10.]])
PublicEncodedTensor([[ -5.]
 [  0.]
 [  7.]
 [ 16.]])
PublicEncodedTensor([[ -5.  -6.  -7.  -8.]
 [  0.   0.   0.   0.]
 [  5.   6.   7.   8.]
 [ 10.  12.  14.  16.]])
PublicEncodedTensor([[ 10.  12.  14.  16.]])


In [13]:
# class EncodedTensor:
    
#     def __init__(self, values, elements=None):
#         if not elements is None:
#             assert isinstance(elements, FieldTensor)
#             self.elements = elements
#         else:
#             if not isinstance(values, np.ndarray): values = np.array([values])
#             self.elements = FieldTensor(encode(values))
    
#     @property
#     def shape(self):
#         return self.elements.shape
    
#     def __repr__(self):
#         return "EncodedTensor(%s)" % decode(self.elements)
    
#     def with_elements(elements):
#         return EncodedTensor(None, elements)
    
#     def truncate(self, amount=PRECISION_FRACTIONAL):        
#         truncate = np.vectorize(lambda x: x // BASE**amount if x <= Q/2 else Q - ((Q - x) // BASE**amount))
#         return EncodedTensor.with_elements(truncate(self.elements))
    
#     def add(x, y):
#         if isinstance(y, EncodedTensor):
#             return EncodedTensor.with_elements((x.elements + y.elements) % Q)
#         elif isinstance(y, PrivateTensor):
#             shares0 = (x.elements + y.shares0) % Q
#             shares1 =               y.shares1
#             return PrivateTensor.with_shares(shares0, shares1)
#         else:
#             raise TypeError(type(y))
        
#     def __add__(x, y):
#         return x.add(y)
        
#     def sub(x, y):
#         if isinstance(y, EncodedTensor):
#             return EncodedTensor.with_elements((x.elements - y.elements) % Q)
#         elif isinstance(y, PrivateTensor):
#             # TODO might be more efficient way
#             shares0 = ((Q-1) * y.shares0 + x.elements) % Q
#             shares1 = ((Q-1) * y.shares1) % Q
#             return PrivateTensor.with_shares(shares0, shares1)
#         else:
#             raise TypeError(type(y))
        
#     def __sub__(x, y):
#         return x.sub(y)
        
#     def mul(x, y, truncate=True):
#         if isinstance(y, EncodedTensor):
#             z = EncodedTensor.with_elements((x.elements * y.elements) % Q)
#             if truncate: z = z.truncate()
#             return z
#         elif isinstance(y, PrivateTensor):
#             shares0 = (x.elements * y.shares0) % Q
#             shares1 = (x.elements * y.shares1) % Q
#             z = PrivateTensor.with_shares(shares0, shares1)
#             if truncate: z = z.truncate()
#             return z
#         else:
#             raise TypeError(type(y))
    
#     def __mul__(x, y):
#         return x.mul(y)
    
#     def div(x, y):
#         if isinstance(y, EncodedTensor):
#             return EncodedTensor(decode(x.elements) / decode(y.elements))
#         elif isinstance(y, int) or isinstance(y, float) or isinstance(y, np.ndarray):
#             return EncodedTensor(decode(x.elements) / y)
#         else:
#             raise TypeError(type(y))
        
#     def __div__(x, y):
#         return x.div(y)
    
#     def dot(x, y, truncate=True):
#         if isinstance(y, EncodedTensor):
#             z = EncodedTensor.with_elements(x.elements.dot(y.elements) % Q)
#             if truncate: z = z.truncate()
#             return z
#         elif isinstance(y, PrivateTensor):
#             shares0 = x.elements.dot(y.shares0) % Q
#             shares1 = x.elements.dot(y.shares1) % Q
#             z = PrivateTensor.with_shares(shares0, shares1)
#             if truncate: z = z.truncate()
#             return z
#         else:
#             raise TypeError(type(y))
        
#     def transpose(x):
#         return EncodedTensor.with_elements(x.elements.T)
    
#     def sum0(x):
#         return EncodedTensor.with_elements(x.elements.sum(axis=0, keepdims=True))
    
#     def sum1(x):
#         return EncodedTensor.with_elements(x.elements.sum(axis=1, keepdims=True))
        
#     def exp(x):
#         return EncodedTensor(np.exp(decode(x.elements)))
    
#     def __getitem__(x, index):
#         return EncodedTensor.with_elements(x.elements[index])

In [14]:
# x = EncodedTensor(np.array([1,2,3,4]).reshape(4,1) - 2); print(x)
# y = EncodedTensor(np.array([5,6,7,8]).reshape(4,1)); print(y)
# z = x + y; print(z)
# z = (x * y); print(z)
# z = x.dot(y.transpose()); print(z)
# z = z.sum0(); print(z)

In [15]:
def generate_mul_triple(shape):
    a = np.array([ random.randrange(Q) for _ in range(np.prod(shape)) ]).astype(DTYPE).reshape(shape)
    b = np.array([ random.randrange(Q) for _ in range(np.prod(shape)) ]).astype(DTYPE).reshape(shape)
    ab = (a * b) % Q
    return SharedFieldTensor.from_elements(a), \
           SharedFieldTensor.from_elements(b), \
           SharedFieldTensor.from_elements(ab)

In [16]:
def generate_dot_triple(m, n, o):
    a = np.array([ random.randrange(Q) for _ in range(m*n) ]).astype(DTYPE).reshape((m,n))
    b = np.array([ random.randrange(Q) for _ in range(n*o) ]).astype(DTYPE).reshape((n,o))
    ab = np.dot(a, b)
    return SharedFieldTensor.from_elements(a), \
           SharedFieldTensor.from_elements(b), \
           SharedFieldTensor.from_elements(ab)

In [47]:
class SharedEncodedTensor:
    
    def __init__(self, values, shares0=[], shares1=[]):
        if values is not None:
            if not isinstance(values, np.ndarray):
                values = np.array(values)
            shares0, shares1 = share(encode(values))
        self.shares0 = shares0
        self.shares1 = shares1
        assert self.shares0.shape == self.shares1.shape
    
    def from_values(values):
        return SharedEncodedTensor(values)
    
    def from_elements(elements):
        shares0, shares1 = share(elements)
        return SharedEncodedTensor(None, shares0, shares1)
    
    def from_shares(shares0, shares1):
        return SharedEncodedTensor(None, shares0, shares1)
    
    def unwrap(self):
        return decode((self.shares0 + self.shares1) % Q)
    
#     def reveal(self):
#         return PublicEncodedTensor.from_elements((self.shares0 + self.shares1) % Q)
    
    def __repr__(self):
        elements = (self.shares0 + self.shares1) % Q
        return "SharedEncodedTensor(%s)" % decode(elements)
    
    def __getitem__(self, index):
        return SharedEncodedTensor.from_shares(self.shares0[index], self.shares1[index])
    
    @property
    def shape(self):
        return self.shares0.shape
    
    def truncate(self, amount=PRECISION_FRACTIONAL):
        shares0 = np.floor_divide(self.shares0, BASE**amount) % Q
        shares1 = (Q - (np.floor_divide(Q - self.shares1, BASE**amount))) % Q
        return SharedEncodedTensor.from_shares(shares0, shares1)
    
    def add(x, y):
        if isinstance(y, SharedEncodedTensor):
            shares0 = (x.shares0 + y.shares0) % Q
            shares1 = (x.shares1 + y.shares1) % Q
            return SharedEncodedTensor.from_shares(shares0, shares1)
        
        elif isinstance(y, PublicEncodedTensor):
            shares0 = (x.shares0 + y.elements) % Q
            shares1 =  x.shares1
            return SharedEncodedTensor.from_shares(shares0, shares1)
        
        elif isinstance(y, int) or isinstance(y, float) or isinstance(y, np.ndarray):
            return x.add(PublicEncodedTensor.from_values(y))
        
        else:
            raise TypeError(type(y))
        
    def __add__(x, y):
        return x.add(y)
    
    def sub(x, y):
        if isinstance(y, SharedEncodedTensor):
            shares0 = (x.shares0 - y.shares0) % Q
            shares1 = (x.shares1 - y.shares1) % Q
            return SharedEncodedTensor.from_shares(shares0, shares1)
        
        elif isinstance(y, PublicEncodedTensor):
            shares0 = (x.shares0 - y.elements) % Q
            shares1 =  x.shares1
            return SharedEncodedTensor.from_shares(shares0, shares1)
        
        elif isinstance(y, int) or isinstance(y, float) or isinstance(y, np.ndarray):
            return x.sub(PublicEncodedTensor.from_values(y))
        
        elif isinstance(y, SharedFieldTensor):
            shares0 = (x.shares0 - y.shares0) % Q
            shares1 = (x.shares1 - y.shares1) % Q
            return SharedFieldTensor.from_shares(shares0, shares1)
        
        else:
            raise TypeError(type(y))
        
    def __sub__(x, y):
        return x.sub(y)
    
    def mul(x, y, precomputed=None):
        if isinstance(y, SharedEncodedTensor):
            if precomputed is None: precomputed = generate_mul_triple(x.shape)
            a, b, ab = precomputed
            assert x.shape == y.shape
            assert x.shape == a.shape
            assert y.shape == b.shape
            alpha = (x - a).reveal()
            beta  = (y - b).reveal()
            z = alpha.mul(beta) + \
                alpha.mul(b) + \
                a.mul(beta) + \
                ab
            return SharedEncodedTensor.from_shares(z.shares0, z.shares1).truncate()
        
        elif isinstance(y, PublicEncodedTensor):
            shares0 = (x.shares0 * y.elements) % Q
            shares1 = (x.shares1 * y.elements) % Q
            return SharedEncodedTensor.from_shares(shares0, shares1)
        
        elif isinstance(y, int) or isinstance(y, float) or isinstance(y, np.ndarray):
            return x.mul(PublicEncodedTensor.from_values(y))
        
        elif isinstance(y, SharedFieldTensor):
            shares0 = (x.shares0 * y.shares0) % Q
            shares1 = (x.shares1 * y.shares1) % Q
            return SharedFieldTensor.from_shares(shares0, shares1)
        
        elif isinstance(y, PublicFieldTensor):
            shares0 = (x.shares0 * y.elements) % Q
            shares1 = (x.shares1 * y.elements) % Q
            return SharedFieldTensor.from_shares(shares0, shares1)
        
        else:
            raise TypeError(type(y))
        
    def __mul__(x, y):
        return x.mul(y)
    
    def dot(x, y, precomputed=None):
        if isinstance(y, SharedEncodedTensor):
            m = x.shape[0]
            n = x.shape[1]
            o = y.shape[1]
            assert n == y.shape[0]
            if precomputed is None: precomputed = generate_dot_triple(m, n, o)
            a, b, ab = precomputed
            alpha = (x - a).reveal()
            beta  = (y - b).reveal()
            z = alpha.dot(beta) + \
                alpha.dot(b) + \
                a.dot(beta) + \
                ab
            return SharedEncodedTensor.from_shares(z.shares0, z.shares1).truncate()
        
        elif isinstance(y, PublicEncodedTensor):
            assert x.shape[1] == y.shape[0]
            shares0 = x.shares0.dot(y.elements) % Q
            shares1 = x.shares1.dot(y.elements) % Q
            return SharedEncodedTensor.from_shares(shares0, shares1).truncate()
        
        elif isinstance(y, int) or isinstance(y, float) or isinstance(y, np.ndarray):
            return x.dot(PublicEncodedTensor.from_values(y))
        
        else:
            raise TypeError(type(y))
        
    def neg(self):
        minus_one = PublicFieldTensor.from_elements(np.array([Q - 1]))
        z = self.mul(minus_one)
        return SharedEncodedTensor.from_shares(z.shares0, z.shares1)
        
    def transpose(self):
        return SharedEncodedTensor.from_shares(self.shares0.T, self.shares1.T)
    
    def sum0(self):
        shares0 = self.shares0.sum(axis=0, keepdims=True) % Q
        shares1 = self.shares1.sum(axis=0, keepdims=True) % Q
        return SharedEncodedTensor.from_shares(shares0, shares1)

In [49]:
x = SharedEncodedTensor(np.array([1,2,3,4]).reshape(4,1) - 2)
y = SharedEncodedTensor(np.array([5,6,7,8]).reshape(4,1))
z = x + y; print(z)
z = (x * y); print(z)
z = x.dot(y.transpose()); print(z)
z = z.sum0(); print(z)

SharedEncodedTensor([[  4.]
 [  6.]
 [  8.]
 [ 10.]])
SharedEncodedTensor([[ -5.]
 [  0.]
 [  7.]
 [ 16.]])
SharedEncodedTensor([[ -5.  -6.  -7.  -8.]
 [  0.   0.   0.   0.]
 [  5.   6.   7.   8.]
 [ 10.  12.  14.  16.]])
SharedEncodedTensor([[ 10.  12.  14.  16.]])


In [19]:
# class PrivateEncodedTensor:
    
#     def __init__(self, values, apply_encoding=True, shares0=None, shares1=None):
#         if shares0 is not None and shares1 is not None:
#             self.shares0 = shares0
#             self.shares1 = shares1
#         else:
#             if apply_encoding: values = encode(values)
#             self.shares0 = np.array([ random.randrange(Q) for _ in range(values.size) ]).astype(DTYPE).reshape(values.shape)
#             self.shares1 = (values - self.shares0) % Q
        
#     def with_shares(shares0, shares1):
#         return PrivateTensor(None, False, shares0, shares1)
    
#     def reveal(self):
#         values = (self.shares0 + self.shares1) % Q
#         return EncodedTensor.with_elements(values)
    
#     def truncate(self, amount=PRECISION_FRACTIONAL):
#         # TODO truncation doesn't work if there are 0 values -- assert this?
#         shares0 = np.floor_divide(self.shares0, BASE**amount) % Q
#         shares1 = (Q - (np.floor_divide(Q - self.shares1, BASE**amount))) % Q
#         return PrivateTensor.with_shares(shares0, shares1)
    
#     def __repr__(self):
#         return "PrivateTensor(%s)" % decode(self.reveal().elements)
    
#     @property
#     def shape(self):
#         return self.shares0.shape
    
#     def add(x, y):
#         if isinstance(y, PrivateEncodedTensor):
#             shares0 = (x.shares0 + y.shares0) % Q
#             shares1 = (x.shares1 + y.shares1) % Q
#             return PrivateEncodedTensor.with_shares(shares0, shares1)
#         elif isinstance(y, EncodedTensor):
#             shares0 = (x.shares0 + y.elements) % Q
#             shares1 =  x.shares1
#             return PrivateTensor.with_shares(shares0, shares1)
#         elif isinstance(y, int) or isinstance(y, float) or isinstance(y, np.ndarray):
#             return x.add(EncodedTensor(y))
#         else:
#             raise TypeError(type(y))
        
#     def __add__(x, y):
#         return x.add(y)
    
#     def sub(x, y):
#         if isinstance(y, PrivateTensor):
#             shares0 = (x.shares0 - y.shares0) % Q
#             shares1 = (x.shares1 - y.shares1) % Q
#             return PrivateTensor.with_shares(shares0, shares1)
#         elif isinstance(y, EncodedTensor):
#             shares0 = (x.shares0 - y.values) % Q
#             shares1 =  x.shares1
#             return PrivateTensor.with_shares(shares0, shares1)
#         elif isinstance(y, int) or isinstance(y, float) or isinstance(y, np.ndarray):
#             return x.sub(EncodedTensor(y))
#         else:
#             raise TypeError(type(y))
        
#     def __sub__(x, y):
#         return x.sub(y)
    
#     def mul(x, y, truncate=True, precomputed=None):
#         if isinstance(y, PrivateTensor):
#             assert x.shares0.shape == x.shares1.shape == y.shares0.shape == y.shares1.shape
#             if precomputed is None: precomputed = generate_mul_triple(x.shares0.shape)
#             a, b, ab = precomputed
#             assert x.shape == a.shape
#             assert y.shape == b.shape
#             alpha = (x - a).reveal()
#             beta  = (y - b).reveal()
#             z = alpha.mul(beta, truncate=False) + \
#                 alpha.mul(b, truncate=False) + \
#                 a.mul(beta, truncate=False) + \
#                 ab
#             if truncate: z = z.truncate()
#             return z
#         elif isinstance(y, EncodedTensor):
#             shares0 = (x.shares0 * y.values) % Q
#             shares1 = (x.shares1 * y.values) % Q
#             z = PrivateTensor.with_shares(shares0, shares1)
#             if truncate: z = z.truncate()
#             return z
#         elif isinstance(y, int) or isinstance(y, float) or isinstance(y, np.ndarray):
#             return x.mul(EncodedTensor(y), truncate, precomputed)
#         else:
#             raise TypeError(type(y))
        
#     def __mul__(x, y):
#         return x.mul(y)
        
#     def dot(x, y, truncate=True, precomputed=None):
#         if isinstance(y, PrivateTensor):
#             m = x.shares0.shape[0]
#             n = x.shares0.shape[1]
#             o = y.shares0.shape[1]
#             assert n == y.shares0.shape[0]
#             if precomputed is None: precomputed = generate_dot_triple(m, n, o)
#             a, b, ab = precomputed
#             alpha = (x - a).reveal()
#             beta  = (y - b).reveal()
#             z = alpha.dot(beta, truncate=False) + \
#                 alpha.dot(b, truncate=False) + \
#                 a.dot(beta, truncate=False) + \
#                 ab
#             if truncate: z = z.truncate()
#             return z
#         elif isinstance(y, EncodedTensor):
#             assert x.shares0.shape == x.shares1.shape
#             assert x.shares0.shape[0] == y.shape[1]
#             shares0 = x.shares0.dot(y.values) % Q
#             shares1 = x.shares1.dot(y.values) % Q
#             z = PrivateTensor.with_shares(shares0, shares1)
#             if truncate: z = z.truncate()
#             return z
#         elif isinstance(y, int) or isinstance(y, float) or isinstance(y, np.ndarray):
#             return x.dot(EncodedTensor(y))
#         else:
#             raise TypeError(type(y))
        
#     def neg(self):
#         return self.mul(EncodedTensor.with_elements(np.array([Q - 1])), truncate=False)
        
#     def transpose(self):
#         return PrivateTensor.with_shares(self.shares0.T, self.shares1.T)
    
#     def sum0(self):
#         shares0 = self.shares0.sum(axis=0, keepdims=True) % Q
#         shares1 = self.shares1.sum(axis=0, keepdims=True) % Q
#         return PrivateTensor.with_shares(shares0, shares1)
    
#     def __getitem__(x, index):
#         return PrivateTensor.with_shares(x.shares0[index], x.shares1[index])

In [20]:
# x = PrivateTensor(np.array([1,2,3,4]).reshape(4,1) - 2)
# y = PrivateTensor(np.array([5,6,7,8]).reshape(4,1))
# z = x + y; print(z)
# z = (x * y); print(z)
# z = x.dot(y.transpose()); print(z)
# z = z.sum0(); print(z)

In [96]:
x = np.array(10)
isinstance(x, np.ndarray)

True

In [100]:
encode(np.array([0.0001825597]))

array([784087], dtype=object)